# Generated by Django 3.1.4 on 2021-06-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
